import unittest

from writedown.ast import PartNode, DocumentNode
from writedown.parser import Parser

class TestPart(unittest.TestCase):
    def test_no_number_or_title(self):
        doc = Parser().parse_doc("@part")

        self.assertIsInstance(doc, DocumentNode)
        self.assertEqual(len(doc.nodes), 1)

        part = doc.nodes[0]
        self.assertIsInstance(part, PartNode)
        self.assertEqual(part.number, 1) # Autogenerated
        self.assertEqual(part.title, None)

    def test_number_and_title(self):
        doc = Parser().parse_doc("@part 1 One")

        self.assertIsInstance(doc, DocumentNode)
        self.assertEqual(len(doc.nodes), 1)

        part = doc.nodes[0]
        self.assertIsInstance(part, PartNode)
        self.assertEqual(part.number, 1)
        self.assertEqual(part.title, "One")

    def test_number(self):
        doc = Parser().parse_doc("@part 1")

        self.assertIsInstance(doc, DocumentNode)
        self.assertEqual(len(doc.nodes), 1)

        part = doc.nodes[0]
        self.assertIsInstance(part, PartNode)
        self.assertEqual(part.number, 1)
        self.assertEqual(part.title, None)

    def test_title(self):
        doc = Parser().parse_doc("@part One")

        self.assertIsInstance(doc, DocumentNode)
        self.assertEqual(len(doc.nodes), 1)

        part = doc.nodes[0]
        self.assertIsInstance(part, PartNode)
        self.assertEqual(part.number, 1) # Autogenerated
        self.assertEqual(part.title, "One")

    def test_multiple(self):
        doc = Parser().parse_doc("""@part One
@part Two""")

        self.assertIsInstance(doc, DocumentNode)
        self.assertEqual(len(doc.nodes), 2)

        part1 = doc.nodes[0]
        self.assertIsInstance(part1, PartNode)
        self.assertEqual(part1.number, 1) # Autogenerated
        self.assertEqual(part1.title, "One")

        part2 = doc.nodes[1]
        self.assertIsInstance(part2, PartNode)
        self.assertEqual(part2.number, 2) # Autogenerated
        self.assertEqual(part2.title, "Two")

if __name__ == '__main__':
    unittest.main()